spring:
  datasource:
    url: jdbc:mysql://localhost:3306/youcontribute
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: create
